### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by jemmail** [paulwetter/DocumentConfigMgrCB#18]
I get an error message

Method invocation failed because [System.Management.ManagementObject] does not contain a method named 'Where'.
At C:\temp\DocumentConfigMgrCB-master\DocumentCMCB.ps1:1285 char:7

**Comment by paulwetter** [comment]
This is where it is collecting information on the DP drives that are used for content.  If you look at what it was able to write in the doc already, did some of your DPs succeed in writing the content drive information?

Couple questions:

1. Build of CM?
2. Where are you running the script from?
3. PowerShell version?
4. Does the script continue and complete for you or does it fail out there completely?
         If it fails and exits there, then, it is hanging up on collecting drive info on a specific DP.  Look at what it wrote so far and see what DP it started writing info on.  Check that DP in the console and make sure it's healthy (drives, content, etc).

This is actually old code from the original script and haven't seen the error before.  So, very interested in figuring it out.

Also, turn on the -Verbose switch.  it should tell which DP it is at just before it errors.

**Comment by ShawnEsterman** [comment]
This is probably because the SMS_DistributionPointDriveInfo is only returning one object. That never triggers the object between the `()` to be an array. The `.Where()` method exists on PowerShell arrays, but not `[System.Management.ManagementObject]`

    $CMDPDrives = (Get-WmiObject -Class SMS_DistributionPointDriveInfo -Namespace root\sms\site_$SiteCode -ComputerName $SMSProvider).Where({$PSItem.NALPath -like "*$CMDPServerName*"})

Changing the script to this should force the results of the `Get-WmiObject` to be in an array and then having the `.Where()` method to exist:

    $CMDPDrives = @(Get-WmiObject -Class SMS_DistributionPointDriveInfo -Namespace root\sms\site_$SiteCode -ComputerName $SMSProvider).Where({$PSItem.NALPath -like "*$CMDPServerName*"})

**Comment by paulwetter** [comment]
Good catch Shawn.  I wasn't thinking of a single drive for content in a CM site.   Updated and tested per your suggestion and should work for @jemmail now.

Just committed v 3.23 (884740d24497406ccc12b33765a93d72ef39d6df).  Should be good now.
