### ISSUE TITLE
Feature request - CSS parameter

### ISSUE THREAD

**Issue by Skatterbrainz** [paulwetter/DocumentConfigMgrCB#23]
Please consider adding a -Css or -StyleSheet parameter to apply custom CSS rules to the output?  Thank you!

**Comment by paulwetter** [comment]
Added to version 3.40.  cbf2768eea9edf55ed49a36c22f06ebe66515b61
Updated to embed the new style sheet.
Added a template style to the repo as a starting point to build your own styles off of it.
