### ISSUE TITLE
Move visual feedback to Write-ProgressEx function

### ISSUE THREAD

**Issue by ChadSimmons** [paulwetter/DocumentConfigMgrCB#26]
Change Write-Host, Write-Output, and Write-Verbose calls to use a Write-ProgressEx function that incorporates Write-Progress, verbose output, and CMTrace style logging.

**Comment by ChadSimmons** [comment]
- [X] Create function
- [X] Replace all instances of Write-Verbose
- [ ] Add additional function calls to display progress throughout the script

**Comment by ChadSimmons** [comment]
Pull Request #21 should resolve this when complete.

**Comment by paulwetter** [comment]
Finally finished this up last month with 1433da399d114d9339df4b4a1a80019f7df5a91b
Hopefully it gets the feel you were thinking of Chad.
