### ISSUE TITLE
Deployment ID

### ISSUE THREAD

**Issue by sobchakw** [paulwetter/DocumentConfigMgrCB#42]
It would be helpful to have the deployment ID for applications in the report.

**Comment by paulwetter** [comment]
Upon inspection of applications.  I have some pretty big holes with apps that i should fill.  Will expand this to retool application collection details.

**Comment by paulwetter** [comment]
This has been added in latest commit ae66a33d89ba1dff336e00d6a4b24f3c2a4d8698
version 3.46
