### ISSUE TITLE
Get-CMSoftwareUpdateDeploymentPackage : Cannot validate argument on parameter 'Id'.

### ISSUE THREAD

**Issue by Crewsr** [paulwetter/DocumentConfigMgrCB#45]
I cannot thank you enough for this amazing script!

I am getting the following message during the script execution, which completes, and was curious if you knew what might cause it. I do not see anything weird in the output file.

Beginning Execution of version 3.42 at: 5:45 PM
Outputting documentation to: C:\Windows\system32\CMDocumentation.html
Get-CMSoftwareUpdateDeploymentPackage : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command 
again.
At \\PATH\DocumentConfigMgrCB-master\DocumentCMCB.ps1:5504 char:68
+ ... entPackage -Id ([xml]$adr.ContentTemplate).ContentActionXML.PackageID
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-CMSoftwareUpdateDeploymentPackage], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ConfigurationManagement.Cmdlets.Sum.Commands.GetSoftwareUpdateDeploymentPackageCommand
 
Completed execution at: 5:59 PM.
Total execution time: 13 minute(s), and 35 second(s).

**Comment by paulwetter** [comment]
Hmmm... I'll have to test this.  But, I'm guessing that you have an ADR that doesn't download the updates into a package.  Will test and update.

**Comment by Crewsr** [comment]
You are 100% correct, sir! Thank you for pointing me in the right direction to resolve.


-------- Original message --------

**Comment by paulwetter** [comment]
But note that it is perfectly fine to have an ADR without a package. So, something I need to address in the script. Thanks for following up!

**Comment by paulwetter** [comment]
This should be fixed in the latest commit.  07aab1998b99b8cc3ab4abfb7e941a38e4dbad9f
Version 3.44
