### ISSUE TITLE
Enhanced Detection Methods

### ISSUE THREAD

**Issue by CometCom1** [paulwetter/DocumentConfigMgrCB#53]
I've recently found you wonderful script, but I wanted additional information on the applications, which currently only documents the standard MSI detection.

I've crudely expanded the section of the code, to include Enhanced MSI detection, File and Folder detections, Registry detections.
I'd like to contribute this code to the project for everyone to enjoy.

Regards
Kent Komeri

**Comment by CometCom1** [comment]
I have tested my extensions to the script in versions 1902, 1906 and 1910 without issues.
Examples
MSI enhanced, no rules:
<P style="margin-left:55px;"><Div style="margin-left:60px;">Detection Method</div><UL style="margin-left:55px;margin-top:0px;"><LI>Using enhanced MSI detection method.</LI><LI>MSI Product Code: {0616A587-A3C3-42AA-828B-2FC857FE91E4}</LI></UL></P>
MSI enhanced, with rule:
<P style="margin-left:55px;"><Div style="margin-left:60px;">Detection Method</div><UL style="margin-left:55px;margin-top:0px;"><LI>Using enhanced MSI detection method.</LI><LI>MSI Product Code: {0C524D20-1409-0080-8A9E-0C4C490E4E54}</LI><LI>Version Equals 8.2</LI></UL></P>
File detection, no rules:
<P style="margin-left:55px;"><Div style="margin-left:60px;">Detection Method</div><UL style="margin-left:55px;margin-top:0px;"><LI>Using File detection method.</LI><LI>FILE Path: %windir%\system32</LI><LI>FILE Name: CMTrace.exe</LI><LI>32-bit</LI></UL></P>
Folder detection, no rules:
<P style="margin-left:55px;"><Div style="margin-left:60px;">Detection Method</div><UL style="margin-left:55px;margin-top:0px;"><LI>Using Folder detection method.</LI><LI>FOLDER Path: C:\Program Files (x86)\Java\</LI><LI>FOLDER Name: jre1.8.0_201</LI><LI>32-bit</LI></UL></P>
Simple registry detection with rule:
<P style="margin-left:55px;"><Div style="margin-left:60px;">Detection Method</div><UL style="margin-left:55px;margin-top:0px;"><LI>Using Simple Registry detection method.</LI><LI>Simple Hive: HKEY_LOCAL_MACHINE</LI><LI>Simple Key : SOFTWARE\Wow6432Node\Microsoft\EdgeUpdate\Clients\{56eb18f8-b008-4cbd-b6d2-8c97fe7e9062}</LI><LI>Property   : pv</LI><LI>Version GreaterEquals 80.0.361.56</LI></UL></P>
Registry detection, no rules:
<P style="margin-left:55px;"><Div style="margin-left:60px;">Detection Method</div><UL style="margin-left:55px;margin-top:0px;"><LI>Using Registry detection method.</LI><LI>Registry Hive: HKEY_LOCAL_MACHINE</LI><LI>Registry Key : Software\Microsoft\Windows\CurrentVersion\Uninstall\O365ProPlusRetail - da-dk</LI></UL></P>

**I have also added a little ekstra on application usage, in case you are interested:**
<P style="margin-left:45px;"><Div style="margin-left:50px;">Application Usage</div><UL style="margin-left:45px;margin-top:0px;"><LI>Devices with application: 9</LI><LI>Devices failed this app : 0</LI><LI>Users with application  : 7</LI><LI>Users failed this app   : 0</LI><LI>Pending user requests   : 14</LI></UL></P>

**Comment by paulwetter** [comment]
Ooooo! Oooooo!  Very interested.  Something I looked at but didn't have the energy to tackle the last time i redid apps.  I'd love to see the code and add it to the script!  Fork this repo, update with your code and then put in a pull request.  If you're not familiar with git share it via onedrive or something and I can add it and credit you for it in the code.

**Comment by CometCom1** [comment]
Pulled and ready for review.
It's a very long time since I worked with github.

**Comment by paulwetter** [comment]
Good deal.  I'll hopefully have a chance to look at it this weekend.  At first glance though, i'm a little excited to see the additional details!

**Comment by paulwetter** [comment]
Completed a full implementation of this with a recursive function in 215adfaad1ab55731b478c4012996d65934a61c4.
Using divs to outline and color code for complex detection methods.  I think I've covered most cases.  And in most instances, one will never see a detection method this complex.
![image](https://user-images.githubusercontent.com/12662223/161375412-4dd99131-4b50-4354-8b6b-297905ad2ec1.png)
