### ISSUE TITLE
Invalid argument error

### ISSUE THREAD

**Issue by JaeBee64** [paulwetter/DocumentConfigMgrCB#60]
Getting the following error when the script hits the Applications section (error occurs mutliple time)

Get-PWCMPhasedDeployment : Cannot validate argument on parameter 'SiteName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At E:\Scripts\DocumentConfigMgrCB-master\DocumentCMCB.ps1:6690 char:113
+ ... entObjectID $($App.CI_ID) -SiteServer $SiteServer -SiteName $SiteName
+                                                                 ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-PWCMPhasedDeployment], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-PWCMPhasedDeployment

And also getting the following errror when processing Task Sequences:

Get-WmiObject : Invalid namespace "Root\SMS\site_DC1"
At E:\Scripts\DocumentConfigMgrCB-master\DocumentCMCB.ps1:7509 char:33
+ ... eferences = Get-WmiObject -Namespace "Root\SMS\site_$($SiteCode)" -Qu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

Script is still writing to the output file, just errors popping up in the console window. We're running CM1910, site version 5.0.8913.1000, single Primary Site. We're using v3.52 of your script

**Comment by paulwetter** [comment]
Are you running it remotely of the primary site server?

**Comment by paulwetter** [comment]
Update Line 6690:
$PDs = Get-PWCMPhasedDeployment -DeploymentObjectID $($App.CI_ID) -SiteServer $SiteServer -SiteName $SiteCode

**Comment by JaeBee64** [comment]
Yes I was, we have a separate script server for running all scripts.

**Comment by paulwetter** [comment]
7509: Missing -ComputerName parameter for WMI Query.

**Comment by JaeBee64** [comment]
Ok, thanks for those. I’ll make the specified changes & let you know.

**Comment by paulwetter** [comment]
Well.... I must have fallen asleep on the couch before I commented.  Latest commit v3.53 (f6715806d3105a035fb0675a3a2df8562dc8d190) has those changes applied.  See if that does the trick.

**Comment by JaeBee64** [comment]
Grabbed your latest script and tried again. Still 1 error:

Get-WmiObject : The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
At E:\Scripts\DocumentConfigMgrCB-master\DocumentCMCB.ps1:1950 char:16
+ ...      $PDs = Get-WmiObject -Query "SELECT * FROM SMS_PhasedDeployment  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : GetWMICOMException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

**Comment by paulwetter** [comment]
I made a few additional minor bug fixes. Now version 3.54.  But, not related to that line giving you the error.  It actually looks like an issue with remote WMI from the server you are running it.  Can you run wmi queries against your Site server from the server running the scripts?

Try the following query.  Replace ABC with your CM site code and ServerName with the name of your server.

`Get-WmiObject -Query "SELECT * FROM SMS_PhasedDeployment" -Namespace "ROOT\SMS\site_ABC" -ComputerName ServerName`

**Comment by JaeBee64** [comment]
I ran the command on the remote server that’s running the script and didn’t receive any errors. I’ll grab your latest script version anyway & try again.

**Comment by paulwetter** [comment]
How's this issue looking for you? The latest build resolve all the errors?

**Comment by JaeBee64** [comment]
Sorry, I meant to reply to you earlier. Unfortunately it didn’t fix the problem.

**Comment by paulwetter** [comment]
With the latest script, could you re-post the exact error again?  Maybe try running the verbose switch to see what else is going on around at the time....

**Comment by JaeBee64** [comment]
I’ve r-run the script, below is the error:


Get-WmiObject : The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
At E:\Scripts\DocumentConfigMgrCB-master\DocumentCMCB.ps1:1950 char:16
+ ...      $PDs = Get-WmiObject -Query "SELECT * FROM SMS_PhasedDeployment  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : GetWMICOMException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

**Comment by ChadSimmons** [comment]
Doing some validation... Running from a remote Win10 computer and a v2002 stand-alone Primary site , I'm able to run the direct WMI query with error

`Get-WmiObject -Query "SELECT * FROM SMS_PhasedDeployment" -Namespace "ROOT\SMS\site_$SiteName" -ComputerName $SiteServer`

I ran DocumentConfigMgrCB.ps1 version 3.54 and did not experience the issue, but the site does not have any phased deployments configured.

**Comment by paulwetter** [comment]
What i don't get is how this is the only one that fails.  There are other WMI queries that seemingly are running remotely fine.  and if he runs it directly, in powershell, no error... So, I'm missing something to this puzzle. it doesn't add up.

JaeBee64,
What account is the script running as?  What permission does it have to CM?

**Comment by JaeBee64** [comment]
The account has full Administrator access to CM. Also to add to the mystery, we don’t actually have any phased deployments. Could this likely be arising from some error in the SCCM setup? It was setup before I started working here.

**Comment by paulwetter** [comment]
Wild thought here... Are phased deployments actually enabled in you site under Updates and Servicing, Features?

**Comment by JaeBee64** [comment]
We don’t have that option to enable, we’ve recently upgraded to 2002. Phased deployments are available for us to use when deploying apps & Task Sequences however. I’ve attached screenshots, hope they come through.

[cid:image001.png@01D66BDC.227B2040]

[cid:image002.png@01D66BDC.645138B0]

**Comment by paulwetter** [comment]
Ok.....  Stupid mistake on my part.  Not sure why i wasn't seeing it as well in testing.

Anyway.  Try version 3.56.

**Comment by JaeBee64** [comment]
Hi,

Apologies for the lag in my reply. I ‘ve run the 3.56 version of the script but still getting the following errors:

Object reference not set to an instance of an object.
At E:\Scripts\DocumentConfigMgrCB-master\DocumentCMCB.ps1:5575 char:13
+             $ExcludeRules = $DeviceCollection | Get-CMDeviceCollectio ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException
Object reference not set to an instance of an object.
At E:\Scripts\DocumentConfigMgrCB-master\DocumentCMCB.ps1:5590 char:13
+             Write-HTMLParagraph -Level 4 -File $FilePath -Text '<b>Di ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException
Object reference not set to an instance of an object.
At E:\Scripts\DocumentConfigMgrCB-master\DocumentCMCB.ps1:7317 char:17
+ ...             Write-HtmlList -Title $PackageName -Description $PackageD ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException
Object reference not set to an instance of an object.
At E:\Scripts\DocumentConfigMgrCB-master\DocumentCMCB.ps1:7356 char:25
+ ...             Write-HtmlTable -InputObject $DriverArray -Border 1 -Leve ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException

**Comment by paulwetter** [comment]
These look like new errors in totally different area of script.

The error on line 5590 makes no sense as it is just writing a line of text to the file.

Same for 7356.  I am validating that $DriverPackages is not null or empty before writing..

The other 2 locations I tweaked a little but didn't/don't run into errors with them before or now.
* Exclude Membership rules on collections.
* Description on Driver Packages.

Try the new version and see if it makes a difference for these new errors.

**Comment by paulwetter** [comment]
@JaeBee64 you have any follow up on previous issues?  These still exist, or have they been resolved?

**Comment by JaeBee64** [comment]
Hi Paul,

Apologies, been flat out with stuff. I’ve downloaded & run v3.60 of your script and it completed without any errors at all. Thanks for following up with this.

Cheers

Joe

**Comment by paulwetter** [comment]
Excellent. Glad the latest is working for you now.  Always appreciate the feedback.
