### ISSUE TITLE
Abort script on PSDrive

### ISSUE THREAD

**Issue by DokH** [paulwetter/DocumentConfigMgrCB#65]
Tried the script, but it aborts at the **#CM12 cmdlets need to be run from the CM12 drive** section.
I must admit I did not set up SCCM v1910 that we have, so not sure why it does not find that PSDrive.
$SiteCode was found correctly.

Any suggestions?

**Comment by ChadSimmons** [comment]
If you open a PowerShell console, can you change to the ConfigMgr Site drive?  If not, try running this, then run the script again.

Import-Module ($Env:SMS_ADMIN_UI_PATH.Substring(0, $Env:SMS_ADMIN_UI_PATH.Length - 5) + '\ConfigurationManager.psd1')
New-PSDrive -Name <SiteCode> -PSProvider cmsite -Root <Primary.constoso.com>

**Comment by DokH** [comment]
Thanks Chad.
That did it. 
Hopefully without to much impact on the whole SCCM system.
Just added the <Site Code> after -Name .

Regards,
Koen
