### ISSUE TITLE
minor code glitches

### ISSUE THREAD

**Issue by chriskenis** [paulwetter/DocumentConfigMgrCB#69]
line 5898 adds the wrong values to $listarray--> $filesarray instead of $processarray
lines 4096 and 4075 return an error when schedule object is empty --> propose check on ($null -eq $AgentConfig.Schedule) and ($null -eq $AgentConfig.EvaluationSchedule) to prevent $null validation error from the Convert-CMSchedule cmdlet

**Comment by ChadSimmons** [comment]
- line 5898... great catch and easy fix
- line 4096 & 4075... these are getting the schedule for various settings in a Client Device Setting policy.  What configuration do you have that Software Inventory and Compliance Settings would not have an actual schedule?
- FYI the same code structure exists on line 4350 (Software Metering), line 4371 & 4375 (Software Updates), line 4593 (Hardware Inventory), 4640 (Software Deployment)

**Comment by chriskenis** [comment]
I have ran the script again in debug mode in VSCode and then I did not get the $null error on these lines and neither were the schedules empty or null. I'll keep an eye out next time I run it in production again.

**Comment by ChadSimmons** [comment]
@chriskenis are you planning to submit a pull request for the issue on line 5898?  I thought you might want "credit" for squashing that bug.
