### ISSUE TITLE
Getting "Scripts feature not found in this site. Scripts were introduced with release 1706." running on 2010 

### ISSUE THREAD

**Issue by 5ccm** [paulwetter/DocumentConfigMgrCB#83]
Is there something I need to change on the script for it to detect scripts on my site?  Thanks a lot Sorry didnt know how to label "help wanted"

**Comment by ChadSimmons** [comment]
I ran into this in one environment, but I didn't have access to troubleshoot.  We reran the script a few days later, possibly from a different computer and it worked fine.  Pretty odd though.

**Comment by paulwetter** [comment]
I think it is because scripts are no longer a separate feature that can be enabled in 2010. My check was `Get-CMSiteFeature| Where-Object {$_.FeatureGuid -like '566F8720-F415-4E10-9A51-CDE682BA2B2E'}` and this no longer returns anything in my 2010 installs.  look at a quick fix for that tonight.

**Comment by ChadSimmons** [comment]
> I ran into this in one environment, but I didn't have access to troubleshoot. We reran the script a few days later, possibly from a different computer and it worked fine. Pretty odd though.

Hmm... looks like I misremembered that.  We never ran the script again in that environment.  That's what I get for juggling too many customers and not verifying first.

**Comment by paulwetter** [comment]
Updated version 3.64 of the script will take care of this issue.  Download the latest and test.

**Comment by 5ccm** [comment]
Works perfect thanks a lot!!!
