### ISSUE TITLE
Get-ClientSettingsConfigs is producing an error

### ISSUE THREAD

**Issue by pcchenard** [paulwetter/DocumentConfigMgrCB#88]
The script is producing the following error.  Any guidance would be appreciated.

```
Get-ClientSettingsConfigs : The term 'Get-ClientSettingsConfigs' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\DocumentConfigMgrCB\DocumentCMCB.ps1:5211 char:5
+     Get-ClientSettingsConfigs -AgentConfigs $DefaultCS.AgentConfigura ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ClientSettingsConfigs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by paulwetter** [comment]
Ahhhh... See it. Use the -ListAllInformation for now as a workaround.  I put the function in the middle of a optional block and without that switch, it doesn't create the function.  I'll move things around this weekend to fix it.

**Comment by brunoramosdematos** [comment]
Hi Paul - any chance you had the time to look at this bug yet?
Many thanks in advance! :)

**Comment by paulwetter** [comment]
I haven't fixed it yet.  Been distracted over the summer.  However the workaround should do it.  Please post the exact error text that you are receiving in case I missed something.

**Comment by brunoramosdematos** [comment]
> I haven't fixed it yet. Been distracted over the summer. However the workaround should do it. Please post the exact error text that you are receiving in case I missed something.

Hi Paul - It follows the screenshot with the PowerShell output showing the error below:

![image](https://user-images.githubusercontent.com/84633641/126455125-02e8b9a7-c40c-4d71-8b78-46bca8416ff6.png)

Kind Regs,
Bruno

**Comment by paulwetter** [comment]
I updated but didn't test yet.  Guessing this environment you are running against didn't have any custom client settings, only the default?  Try latest 3.65 version just updated.

**Comment by brunoramosdematos** [comment]
> I updated but didn't test yet. Guessing this environment you are running against didn't have any custom client settings, only the default? Try latest 3.65 version just updated.

Thanks Paul - I will test this out an let you know how it goes.

**Comment by brunoramosdematos** [comment]
> I updated but didn't test yet. Guessing this environment you are running against didn't have any custom client settings, only the default? Try latest 3.65 version just updated.

Hi Paul,

That has definitely fixed it!  :)

Thanks again!

Kind Regs,
Bruno
