### ISSUE TITLE
Question: Picture File share path

### ISSUE THREAD

**Issue by grandslamjmh** [paulwetter/DocumentConfigMgrCB#90]
Should the Match pattern allow Admin shares? Should I just not use a UNC path with a folder ending in $?

Your code Snipit:
`    If (($Path -match '^[A-z]:\\.*(\.png|\.jpg)$') -or ($Path -match '^\\\\*\\.*(\.png|\.jpg)$')){
        If (Test-Path -Path "filesystem::$Path"){
            $EncodedImage = [convert]::ToBase64String((get-content $Path -encoding byte))
        }else{
            Write-Error "Path not found: $path"
            Return $false
        }
    }`

**Comment by paulwetter** [comment]
Are you referring to the CompanyLogo image? Does a unc or admin share path not work?  I thought they should.  But I think I always use http or local path.

**Comment by grandslamjmh** [comment]
Yes I was referring to the companyLogo image. I got it working. Was using jpg when my file was png.
