### ISSUE TITLE
Not listing defender process exclussions, it shows excluded files

### ISSUE THREAD

**Issue by wokkeltje13** [paulwetter/DocumentConfigMgrCB#92]
Line 6435 contains an error I think.
$ProcessArray should be used instead off $filesArray

$ProcessArray = @()
foreach ($ExcludedProcess in $AgentConfig.ExcludedProcesses){
    $ProcessArray += "$($ExcludedProcess)"
}
$listArray += Write-HtmlList -Description 'Excluded processes:' -InputObject **$ProcessArray** -Level 1

**Comment by paulwetter** [comment]
Resolved in version 3.68

**Comment by paulwetter** [comment]
good catch by the way.  Thanks!
